sudo: false
language: python
python:
- '3.5'
- '3.6'
install: pip install tox-travis
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- bash echo "SCRIPT SECTION"
