sudo: false
language: python
cache:
  directories:
  - $HOME/.cache/pip
matrix:
  include:
  - env: TOX_ENV=py35
    python: 3.5
install:
- pip install -U tox
- pip install codecov
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- bash echo "SCRIPT SECTION"
